"""Builds design/brand.html — a visual sheet of every NarcoLens SVG (inlined, so it opens from disk)."""
import json
from pathlib import Path

HERE = Path(__file__).parent
SVG = HERE / "svg"
OUT = HERE.parent.parent / "design" / "brand.html"


def read(name):
    return (SVG / name).read_text(encoding="utf-8")


def sized(markup, w):
    return markup.replace("<svg ", f'<svg style="width:{w}px;height:auto;display:block" ', 1)


def main():
    icons = json.loads((HERE / "icons" / "icons.json").read_text(encoding="utf-8"))
    mark, mark_l = read("mark.svg"), read("mark-light.svg")
    tiles = "".join(
        f'<figure class="ic"><svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2" '
        f'stroke-linecap="round" stroke-linejoin="round"><path d="{d}"/></svg><figcaption>{n}</figcaption></figure>'
        for n, d in sorted(icons.items()))
    sizes = "".join(f'<div class="sz">{sized(mark, s)}<span>{s}px</span></div>' for s in (16, 24, 32, 48, 96, 160))
    fg, bg, mono = read("adaptive-foreground.svg"), read("adaptive-background.svg"), read("adaptive-monochrome.svg")
    masked = lambda shape: (f'<div class="mask {shape}"><div class="layer">{sized(bg,120)}</div><div class="layer">{sized(fg,120)}</div></div>')
    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NarcoLens brand</title>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,400..800&display=swap" rel="stylesheet">
<style>
:root{{--ink:#1B1C1F;--muted:#74777F;--line:#E2E1DC;--surface:#F6F5F2;--brand:#E8590C}}
body{{margin:0;font-family:"Roboto Flex",system-ui,sans-serif;color:var(--ink);background:#fff}}
main{{max-width:1100px;margin:0 auto;padding:40px 24px 80px}}
h1{{font-size:34px;margin:0 0 6px}} h2{{font-size:20px;margin:44px 0 6px}} p{{color:var(--muted);margin:0 0 18px}}
.row{{display:flex;gap:18px;flex-wrap:wrap;align-items:center}}
.card{{border:1px solid var(--line);border-radius:20px;padding:28px;display:flex;align-items:center;justify-content:center;min-height:120px}}
.dark{{background:#0E0F11;border-color:#0E0F11}}
.sz{{display:flex;flex-direction:column;align-items:center;gap:8px;font-size:12px;color:var(--muted)}}
.mask{{width:120px;height:120px;position:relative;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,.18)}}
.mask .layer{{position:absolute;inset:0}}
.circle{{border-radius:50%}} .squircle{{border-radius:34%}} .square{{border-radius:18px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(104px,1fr));gap:10px}}
.ic{{margin:0;border:1px solid var(--line);border-radius:14px;padding:16px 8px 10px;display:flex;flex-direction:column;align-items:center;gap:10px}}
.ic figcaption{{font-size:12px;color:var(--muted);font-family:ui-monospace,monospace}}
.sw{{width:120px;border-radius:14px;overflow:hidden;border:1px solid var(--line);font-size:12px}}
.sw i{{display:block;height:64px}} .sw b{{display:block;padding:8px 10px 0}} .sw span{{display:block;padding:0 10px 10px;color:var(--muted);font-family:ui-monospace,monospace}}
code{{background:var(--surface);padding:2px 6px;border-radius:6px;font-size:13px}}
</style></head><body><main>
<h1>NarcoLens brand</h1><p>Every asset lives in <code>narcolens/brand/svg</code> and <code>narcolens/brand/icons</code>, generated by <code>build_brand.py</code>. Edit there, re-run, and the app picks it up.</p>

<h2>Logo mark</h2><p>Shield (protection, evidence) · drop (reagent) · open ring (the lens that reads it).</p>
<div class="row"><div class="card">{sized(mark,120)}</div><div class="card dark">{sized(mark_l,120)}</div></div>
<div class="row" style="margin-top:18px;align-items:flex-end">{sizes}</div>

<h2>Wordmark</h2><p>Letters are outlined to paths, so no font is needed wherever it's used.</p>
<div class="row"><div class="card" style="flex:1">{sized(read("wordmark.svg"),320)}</div><div class="card dark" style="flex:1">{sized(read("wordmark-light.svg"),320)}</div></div>

<h2>Android app icon</h2><p>Adaptive icon layers (108dp, art inside the 66dp safe zone) shown under common launcher masks, the themed-icon monochrome layer, and the 512px Play Store icon.</p>
<div class="row">{masked("circle")}{masked("squircle")}{masked("square")}
  <div class="mask circle" style="background:#DCE3F5"><div class="layer" style="opacity:.75">{sized(mono,120)}</div></div>
  <div style="width:120px">{sized(read("app-icon.svg"),120)}</div></div>

<h2>Prahari</h2><p>"The guard" — a geometric owl, the night-watch that never sleeps. In the app its eyes blink when idle, open wide while listening, and it pulses while speaking.</p>
<div class="row"><div class="card">{sized(read("prahari.svg"),120)}</div><div class="card dark">{sized(read("prahari.svg"),120)}</div><div class="card">{sized(read("prahari-badge.svg"),72)}</div>
<div class="row" style="align-items:flex-end">{"".join(f'<div class="sz">{sized(read("prahari.svg"),s)}<span>{s}px</span></div>' for s in (20,28,40,56))}</div></div>

<h2>Colours</h2>
<div class="row">
  <div class="sw"><i style="background:#1B1C1F"></i><b>Ink</b><span>#1B1C1F</span></div>
  <div class="sw"><i style="background:#E8590C"></i><b>Saffron</b><span>#E8590C</span></div>
  <div class="sw"><i style="background:#FFEADB"></i><b>Saffron soft</b><span>#FFEADB</span></div>
  <div class="sw"><i style="background:#C62828"></i><b>Detected</b><span>#C62828</span></div>
  <div class="sw"><i style="background:#138A45"></i><b>Not detected</b><span>#138A45</span></div>
  <div class="sw"><i style="background:#B26A00"></i><b>Unclear</b><span>#B26A00</span></div>
</div>

<h2>UI icons ({len(icons)})</h2><p>24px grid, 2px stroke, round caps, <code>currentColor</code> — so they take any colour.</p>
<div class="grid">{tiles}</div>
</main></body></html>"""
    OUT.write_text(html, encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
